//
//  HomeWorker.swift
//  FBI
//
//  Created by ADMIN on 01/10/19.
//  Copyright (c) 2019 Success Resource Pte Ltd.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class HomeWorker
{
    func getResponse(url: String, header: [String: String], completionHandler: @escaping (Data)->Void)
  {
    let request = NSMutableURLRequest(url: NSURL(string: url)! as URL,
                                            cachePolicy: .useProtocolCachePolicy,
                                        timeoutInterval: 10.0)
    request.httpMethod = "GET"
    request.allHTTPHeaderFields = header

    let session = URLSession.shared
    let dataTask = session.dataTask(with: request as URLRequest, completionHandler: { (data, response, error) -> Void in
      if (error != nil) {
        print(error as! String)
      } else {
        guard let httpData = data else {return}
        completionHandler(httpData)
      }
    })
    dataTask.resume()
  }
}
