//
//  HomePresenter.swift
//  FBI
//
//  Created by ADMIN on 01/10/19.
//  Copyright (c) 2019 Success Resource Pte Ltd.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic
{
    func presentSomething(response: Home.Collections.Response.NewsResponse)
}

class HomePresenter: HomePresentationLogic
{
  weak var viewController: HomeDisplayLogic?
  
  // MARK: Do something
  
    func presentSomething(response: Home.Collections.Response.NewsResponse)
  {
//    let viewModel = Home.Collections.ViewModel()
    viewController?.displayData(viewModel: response)
  }
}
