//
//  HomeInteractor.swift
//  FBI
//
//  Created by ADMIN on 01/10/19.
//  Copyright (c) 2019 Success Resource Pte Ltd.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic
{
  func getResponse(request: Home.Collections.Request)
}

protocol HomeDataStore
{
  //var name: String { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore
{
  var presenter: HomePresentationLogic?
  var worker: HomeWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func getResponse(request: Home.Collections.Request)
  {
    worker = HomeWorker()
    worker?.getResponse(url: request.apiUrl + request.apiKey, header: request.headers){ data in
        do {
            let newsResponse = try JSONDecoder().decode(Home.Collections.Response.NewsResponse.self, from: data)
            self.presenter?.presentSomething(response: newsResponse)
        } catch {
            print(error)
        }
    }
  }
}
