//
//  LoginWorker.swift
//  FBI
//
//  Created by ADMIN on 01/10/19.
//  Copyright (c) 2019 Success Resource Pte Ltd.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class LoginWorker
{
  func doSomeWork()
  {
  }
}
